# Generated by Django 5.1.3 on 2024-11-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(db_column='AdminID', primary_key=True, serialize=False)),
                ('admin_name', models.CharField(db_column='AdminName', max_length=255)),
                ('admin_email', models.CharField(db_column='AdminEmail', max_length=255)),
                ('admin_password', models.CharField(db_column='AdminPassword', max_length=255)),
            ],
            options={
                'db_table': 'Admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.AutoField(db_column='BuyerID', primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(db_column='BuyerName', max_length=255)),
                ('buyer_rating', models.DecimalField(blank=True, db_column='Buyer_rating', decimal_places=1, max_digits=2, null=True)),
                ('total_orders', models.IntegerField(blank=True, db_column='Total_orders', null=True)),
                ('prefferred_delivery_type', models.CharField(blank=True, db_column='Prefferred_delivery_type', max_length=255, null=True)),
                ('activity_status', models.IntegerField(blank=True, db_column='ActivityStatus', null=True)),
            ],
            options={
                'db_table': 'Buyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerContactData',
            fields=[
                ('contact_data_id', models.AutoField(db_column='Contact_dataID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, db_column='Mobile_phone', max_length=255, null=True)),
                ('telegram_id', models.CharField(blank=True, db_column='Telegram_ID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Buyer_Contact_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='category_name', max_length=255)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('contact_data_id', models.AutoField(db_column='Contact_dataID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, db_column='Mobile_phone', max_length=255, null=True)),
                ('telegram_id', models.CharField(blank=True, db_column='Telegram_ID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Contact_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('discount_amount', models.IntegerField(blank=True, db_column='Discount_amount', null=True)),
                ('order_comments', models.CharField(blank=True, db_column='Order_comments', max_length=255, null=True)),
                ('total_price', models.DecimalField(blank=True, db_column='Total_price', decimal_places=2, max_digits=10, null=True)),
                ('order_timestamp', models.DateTimeField(blank=True, db_column='Order_timeStamp', null=True)),
                ('order_status', models.CharField(blank=True, db_column='Order_status', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddresses',
            fields=[
                ('ordering_address', models.CharField(blank=True, db_column='Ordering_Address', max_length=255, null=True)),
                ('delivery_id', models.IntegerField(blank=True, db_column='Delivery_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Delivery_Addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.AutoField(db_column='FarmID', primary_key=True, serialize=False)),
                ('farm_name', models.CharField(db_column='FarmName', max_length=255)),
                ('product_types', models.CharField(blank=True, db_column='Product_types', max_length=255, null=True)),
                ('working_hours', models.CharField(blank=True, db_column='Working_Hours', max_length=255, null=True)),
                ('farm_address', models.CharField(blank=True, db_column='FarmAddress', max_length=255, null=True)),
                ('farm_size', models.IntegerField(db_column='FarmSize')),
            ],
            options={
                'db_table': 'Farm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarmContactData',
            fields=[
                ('contact_data_id', models.AutoField(db_column='Contact_dataID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, db_column='Mobile_phone', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Farm_Contact_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.AutoField(db_column='FarmerID', primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(db_column='FarmerName', max_length=255)),
                ('niche', models.CharField(blank=True, db_column='Niche', max_length=255, null=True)),
                ('total_sold', models.IntegerField(blank=True, db_column='Total_sold', null=True)),
                ('farmer_rating', models.IntegerField(blank=True, db_column='Farmer_Rating', null=True)),
                ('contact_dataid', models.IntegerField(blank=True, db_column='Contact_dataID', null=True)),
                ('farmer_status', models.CharField(blank=True, db_column='FarmerStatus', max_length=255, null=True)),
                ('activity_status', models.IntegerField(blank=True, db_column='ActivityStatus', null=True)),
            ],
            options={
                'db_table': 'Farmer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderingAddresses',
            fields=[
                ('ordering_address', models.CharField(blank=True, db_column='Ordering_Address', max_length=255, null=True)),
                ('order_id', models.IntegerField(blank=True, db_column='Order_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Ordering_Addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('payment_type', models.CharField(blank=True, db_column='Payment_type', max_length=255, null=True)),
                ('payment_timestamp', models.DateTimeField(blank=True, db_column='Payment_timestamp', null=True)),
                ('payment_amount', models.DecimalField(blank=True, db_column='Payment_amount', decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(blank=True, db_column='Payment_status', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='ProductName', max_length=255)),
                ('available_quantity', models.IntegerField(blank=True, db_column='Available_quantity', null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('product_type', models.CharField(blank=True, db_column='Product_type', max_length=255, null=True)),
                ('product_rating', models.DecimalField(blank=True, db_column='Product_rating', decimal_places=1, max_digits=2, null=True)),
                ('date_added', models.DateTimeField(blank=True, db_column='Date_added', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoldTo',
            fields=[
                ('buyer_id', models.OneToOneField(db_column='BuyerID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='market.buyer')),
            ],
            options={
                'db_table': 'Sold_to',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('order_id', models.OneToOneField(db_column='OrderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='market.orders')),
                ('delivery_type', models.CharField(blank=True, db_column='Delivery_type', max_length=255, null=True)),
                ('delivery_route', models.CharField(blank=True, db_column='Delivery_route', max_length=255, null=True)),
                ('delivery_address', models.CharField(db_column='Delivery_address', max_length=255)),
                ('delivery_duration', models.CharField(blank=True, db_column='Delivery_duration', max_length=255, null=True)),
                ('delivery_implementer', models.CharField(blank=True, db_column='Delivery_implementer', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('order_id', models.OneToOneField(db_column='OrderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='market.orders')),
            ],
            options={
                'db_table': 'Includes',
                'managed': False,
            },
        ),
    ]
